name: python3.8env
channels:
  - conda-forge
  - defaults
dependencies:
  - pysocks
  - parso
  - libgfortran-ng
  - zlib
  - gst-plugins-base
  - openh264
  - libclang
  - matplotlib
  - libcblas
  - mako
  - libwebp-base
  - jsonschema
  - gast
  - dbus
  - testpath
  - pillow
  - tornado
  - olefile
  - tk
  - wheel
  - packaging
  - paramz
  - readline
  - ipython
  - prometheus_client
  - seaborn-base
  - qtpy
  - statsmodels
  - cloudpickle
  - kiwisolver
  - ld_impl_linux-64
  - sqlite
  - libxcb
  - tensorflow-base
  - brotlipy
  - expat
  - jupyter
  - libblas
  - entrypoints
  - gmp
  - joblib
  - fontconfig
  - traitlets
  - wcwidth
  - jupyter_console
  - zeromq
  - libtiff
  - zstd
  - importlib-metadata
  - prompt-toolkit
  - werkzeug
  - glib
  - epicscorelibs
  - h5py
  - libssh2
  - prompt_toolkit
  - pyyaml
  - certifi
  - future
  - libffi
  - seaborn
  - krb5
  - binutils_linux-64
  - gstreamer
  - pcre
  - nettle
  - keras-applications
  - libgcc-ng
  - notebook
  - astor
  - pandocfilters
  - pydm
  - pyqt
  - epics-base
  - nbconvert
  - qtconsole
  - bokeh
  - cryptography
  - ffmpeg
  - jupyterlab
  - libpng
  - pandas
  - jpeg
  - libcurl
  - chardet
  - wrapt
  - six
  - defusedxml
  - gxx_linux-64
  - icu
  - xorg-libxdmcp
  - gettext
  - webencodings
  - lcms2
  - keras
  - ninja
  - pip
  - x264
  - pyglet
  - lz4-c
  - ptyprocess
  - pyqtgraph
  - tensorflow-estimator
  - libgpuarray
  - cython
  - ncurses
  - libxkbcommon
  - pyepics
  - conda-pack
  - libiconv
  - cycler
  - gpy
  - qt
  - bleach
  - libstdcxx-ng
  - pycparser
  - libedit
  - libopenblas
  - typing_extensions
  - xorg-libxau
  - pygpu
  - nspr
  - nss
  - absl-py
  - numpy
  - pyparsing
  - matplotlib-base
  - json5
  - gcc_impl_linux-64
  - tensorboard
  - libsodium
  - bzip2
  - tensorflow
  - patsy
  - widgetsnbextension
  - pickleshare
  - liblapack
  - python==3.8.8
  - gxx_impl_linux-64
  - theano
  - ipykernel
  - send2trash
  - gnutls
  - markdown
  - pint
  - pexpect
  - importlib_metadata
  - gym
  - requests
  - keras-preprocessing
  - perl
  - binutils_impl_linux-64
  - pyzmq
  - jupyterlab_server
  - libprotobuf
  - mkl
  - blas
  - mistune
  - python_abi
  - idna
  - markupsafe
  - deap
  - ca-certificates
  - setuptools
  - python-dateutil
  - zipp
  - google-pasta
  - grpcio
  - protobuf
  - pthread-stubs
  - decorator
  - libgomp
  - ipython_genutils
  - xz
  - jinja2
  - gcc_linux-64
  - jupyter_client
  - p4p
  - ipywidgets
  - backcall
  - pytz
  - mkl-service
  - pygments
  - c-ares
  - libllvm9
  - libuuid
  - hdf5
  - ply
  - pyrsistent
  - yaml
  - intel-openmp
  - attrs
  - lame
  - urllib3
  - threadpoolctl
  - cffi
  - jupyter_core
  - libxml2
  - scikit-learn
  - terminado
  - pandoc
  - nbformat
  - termcolor
  - scipy
  - pyopenssl
  - jedi
  - freetype
  - openssl
  - pytables
  - botorch
  - gpytorch
  - pytorch
  - impact-t[build=mpi_openmpi*]
  - lume-impact
  - distributed
  - dask
  - openpmd-beamphysics
  - watchdog
  - bayesian-optimization
  - pyqt5-sip
  - pyqtchart
  - pyqtwebengine
  - pytao
  - typing
  - treelib
  - lxml
  - conda-pack
  - cothread
  - sqlalchemy
  - alembic
  - cx_oracle
  - cmake
  - pytest
  - black
  - tensorflow-probability
  - dm-tree
  - pystan
  - pip:
    - git+git://github.com/slaclab/edmbutton
    - matlab-wrapper
    - git+git://github.com/slaclab/meme
    - git+git://github.com/slaclab/pyca
    - ipaddress
    - Cheetah3
    - opencv-contrib-python==4.2.0.34
