name: python3.8env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=0.12.0
  - aiohttp=3.7.4
  - alsa-lib=1.2.3
  - anyio=2.2.0
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=20.3.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bayesian-optimization=1.1.0
  - binutils_impl_linux-64=2.35.1
  - binutils_linux-64=2.35
  - blas=2.108
  - blas-devel=3.9.0
  - bleach=3.3.0
  - blinker=1.4
  - blosc=1.21.0
  - bokeh=2.3.1
  - botorch=0.4.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - cachetools=4.2.2
  - certifi=2021.5.30
  - cffi=1.14.5
  - chardet=4.0.0
  - click=7.1.2
  - cloudpickle=1.6.0
  - conda-pack=0.6.0
  - cothread=2.16
  - cryptography=3.4.7
  - cx_oracle=8.2.1
  - cycler=0.10.0
  - cython=0.29.23
  - cytoolz=0.11.0
  - dask=2021.4.1
  - dask-core=2021.4.1
  - dbus=1.13.6
  - deap=1.3.1
  - decorator=5.0.7
  - defusedxml=0.7.1
  - deprecation=2.1.0
  - distgen=0.4.4
  - distributed=2021.4.1
  - dm-tree=0.1.5
  - entrypoints=0.3
  - epics-base=7.0.5.0
  - epicscorelibs=7.0.4.99.1.2
  - expat=2.3.0
  - ffmpeg=4.3.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fsspec=2021.4.0
  - future=0.18.2
  - gast=0.3.3
  - gcc_impl_linux-64=9.3.0
  - gcc_linux-64=9.3.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.68.1
  - glib-tools=2.68.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - google-auth=1.30.0
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - gpy=1.9.9
  - gpytorch=1.4.1
  - grpc-cpp=1.37.1
  - grpcio=1.37.1
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.4
  - gxx_impl_linux-64=9.3.0
  - gxx_linux-64=9.3.0
  - gym=0.18.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - heapdict=1.0.1
  - icu=68.1
  - idna=2.10
  - impact-t=2.1
  - importlib-metadata=4.0.1
  - importlib_metadata=4.0.1
  - importlib_resources=5.1.2
  - intel-openmp=2021.2.0
  - ipykernel=5.5.4
  - ipython=7.23.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - jinja2=2.11.3
  - joblib=1.0.1
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter-packaging=0.9.2
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.7.1
  - jupyter_server=1.6.4
  - jupyterlab=3.0.14
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.5.0
  - jupyterlab_widgets=1.0.0
  - keras=2.4.3
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - kernel-headers_linux-64=2.6.32
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.76.1
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-devel_linux-64=9.3.0
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.68.1
  - libgomp=9.3.0
  - libgpuarray=0.7.6
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libllvm9=9.0.1
  - libnghttp2=1.43.0
  - libogg=1.3.4
  - libopenblas=0.3.15
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.2
  - libprotobuf=3.15.8
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-devel_linux-64=9.3.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.10
  - libxslt=1.1.33
  - llvm-openmp=11.1.0
  - locket=0.2.0
  - lume-impact=0.6.1
  - lxml=4.6.3
  - lz4-c=1.9.3
  - lzo=2.10
  - mako=1.1.4
  - markdown=3.3.4
  - markupsafe=1.1.1
  - matplotlib=3.4.1
  - matplotlib-base=3.4.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2020.4
  - mkl-devel=2020.4
  - mkl-include=2020.4
  - mkl-service=2.3.0
  - mock=4.0.3
  - mpi=1.0
  - msgpack-python=1.0.2
  - multidict=5.1.0
  - mysql-common=8.0.23
  - mysql-libs=8.0.23
  - nbclassic=0.2.7
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - nettle=3.6
  - ninja=1.10.2
  - nose=1.3.7
  - notebook=6.3.0
  - nspr=4.30
  - nss=3.64
  - numexpr=2.7.3
  - numpy=1.20.2
  - oauthlib=3.0.1
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openmpi=4.1.1
  - openpmd-beamphysics=0.5.2
  - openssl=1.1.1k
  - opt_einsum=3.3.0
  - p4p=3.5.3
  - packaging=20.9
  - pandas=1.2.4
  - pandoc=2.12
  - pandocfilters=1.4.2
  - paramz=0.9.5
  - parso=0.8.2
  - partd=1.2.0
  - patsy=0.5.1
  - pcre=8.44
  - perl=5.32.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.2
  - pint=0.17
  - pip=21.1.1
  - ply=3.11
  - prometheus_client=0.10.1
  - prompt-toolkit=3.0.18
  - prompt_toolkit=3.0.18
  - protobuf=3.15.8
  - psutil=5.8.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pydm=1.11.1
  - pyepics=3.4.3
  - pyglet=1.5.16
  - pygments=2.9.0
  - pygpu=0.7.6
  - pyjwt=2.1.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtgraph=0.12.1
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytao=0.1.2
  - pytest=6.2.5
  - python=3.8.8
  - python-dateutil=2.8.1
  - python-flatbuffers=1.12
  - python_abi=3.8
  - pytorch=1.7.1
  - pytz=2021.1
  - pyyaml=5.4.1
  - pyzmq=22.0.3
  - qt=5.12.9
  - qtconsole=5.1.0
  - qtpy=1.9.0
  - re2=2021.04.01
  - readline=8.1
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=0.24.2
  - scipy=1.6.3
  - seaborn=0.11.1
  - seaborn-base=0.11.1
  - send2trash=1.5.0
  - setuptools=49.6.0
  - six=1.16.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - sortedcontainers=2.3.0
  - sqlite=3.35.5
  - statsmodels=0.12.2
  - sysroot_linux-64=2.12
  - tblib=1.7.0
  - tensorboard=2.4.1
  - tensorboard-plugin-wit=1.8.0
  - tensorflow=2.4.1
  - tensorflow-base=2.4.1
  - tensorflow-estimator=2.4.0
  - termcolor=1.1.0
  - terminado=0.9.4
  - testpath=0.4.4
  - theano=1.0.5
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tomlkit=0.7.0
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=5.0.5
  - treelib=1.6.1
  - typing=3.10.0.0
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.26.4
  - watchdog=2.1.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - x264=1!161.3030
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zict=2.0.0
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - git+git://github.com/slaclab/edmbutton
    - matlab-wrapper
    - git+git://github.com/slaclab/meme
    - git+git://github.com/slaclab/pyca
    - ipaddress
    - Cheetah3
    - opencv-contrib-python==4.2.0.34