name: python3.8env
channels:
  - conda-forge
  - defaults
dependencies:
  - bmad
  - bayesian-optimization
  - black
  - blosc
  - bokeh
  - botorch
  - cothread
  - cx_oracle
  - dateparser
  - deap
  - dm-tree
  - epics-base
  - epicscorelibs
  - gpflow
  - gpy
  - gym
  - h5py
  - hdf5
  - impact-t
  - ipython
  - ipywidgets
  - jinja2
  - jupyter
  - jupyterlab
  - kafka-python
  - keras
  - lume-impact
  - matplotlib
  - mock
  - mpi
  - notebook
  - numexpr
  - numpy
  - openmpi
  - openpmd-beamphysics
  - pandas
  - pip
  - pint
  - pydm
  - pyepics
  - pyqt
  - pyqtgraph
  - pytao
  - pytest
  - python=3.8
  - pytorch
  - pytz
  - pyzmq
  - qtpy
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - six
  - sqlite
  - pytables
  - tensorflow
  - tensorflow-probability
  - theano
  - treelib
  - pip:
    - git+https://github.com/slaclab/edmbutton
    - git+https://github.com/slaclab/edlgenerator
    - git+https://github.com/slaclab/slacepics
    - git+https://github.com/slaclab/subprocessca
    - git+https://github.com/slaclab/edef
    - matlab-wrapper
    - git+https://github.com/slaclab/meme
    - git+https://github.com/slaclab/pyca
    - git+https://github.com/slaclab/lcls-live
    - git+https://github.com/slaclab/lcls-tools
    - ipaddress
    - Cheetah3
    - p4p  # This is on conda-forge, but not updated. pypi has the latest versions
    - softioc
    - opencv-contrib-python==4.2.0.34
#
# Stuff that isn't on PyPI or GitHub that is manually installed in prod
# epics-batch-get
# gauge-widget
# lcls-parameters
# logicgate
# matlog
# model
# physicselog
# wmctrl
